#!/usr/bin/env python3
"""Validate generated private SFT commands against train_sft_lora.py supported flags.

Parses the JSON output from kimari4b_private_sft_command.py and validates:
- No unsupported flags in training_real
- gate_state == BLOCKED
- public_release_allowed == False
- hf_upload_allowed == False
- No HF upload commands present
- No forbidden_commit_artifacts as committable outputs

Usage:
    python training/scripts/validate_private_sft_commands.py \
        --command-json /tmp/kimari4b_commands.json \
        --training-script training/scripts/train_sft_lora.py \
        --json
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent


def get_supported_flags(training_script: Path) -> set[str]:
    """Get supported flags from train_sft_lora.py --show-supported-flags --json."""
    result = subprocess.run(
        [sys.executable, str(training_script), "--show-supported-flags", "--json"],
        capture_output=True,
        text=True,
        cwd=str(PROJECT_ROOT),
        timeout=30,
    )
    if result.returncode != 0:
        print(f"ERROR: Failed to get supported flags: {result.stderr}", file=sys.stderr)
        sys.exit(1)
    data = json.loads(result.stdout)
    return set(data.get("supported_flags", []))


def extract_flags_from_command(command: str) -> list[str]:
    """Extract flag arguments from a command string."""
    parts = command.split()
    flags = []
    for part in parts:
        if part.startswith("--"):
            # Get just the flag name (before =)
            flag_name = part.split("=")[0]
            flags.append(flag_name)
    return flags


def main() -> None:
    parser = argparse.ArgumentParser(description="Validate generated private SFT commands against supported flags.")
    parser.add_argument(
        "--command-json",
        type=Path,
        required=True,
        help="Path to JSON file generated by kimari4b_private_sft_command.py",
    )
    parser.add_argument(
        "--training-script",
        type=Path,
        default=Path("training/scripts/train_sft_lora.py"),
        help="Path to train_sft_lora.py",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        dest="json_output",
        help="Output structured JSON result",
    )
    args = parser.parse_args()

    # Load command JSON
    command_path = args.command_json
    if not command_path.exists():
        print(f"ERROR: Command JSON not found: {command_path}", file=sys.stderr)
        sys.exit(1)

    with open(command_path) as f:
        commands = json.load(f)

    # Get supported flags
    training_script = args.training_script
    if not training_script.is_absolute():
        training_script = PROJECT_ROOT / training_script

    supported = get_supported_flags(training_script)

    # Validate
    errors: list[str] = []
    warnings: list[str] = []
    checks: dict[str, bool] = {}

    # Check 1: No unsupported flags in training_real
    training_real = commands.get("training_real", [])
    unsupported_found = []
    for cmd in training_real:
        flags = extract_flags_from_command(cmd)
        for flag in flags:
            if flag not in supported:
                unsupported_found.append(flag)
    checks["no_unsupported_flags"] = len(unsupported_found) == 0
    if unsupported_found:
        errors.append(f"Unsupported flags found in training_real: {unsupported_found}")

    # Check 2: gate_state == BLOCKED
    gate_blocked = commands.get("gate_state") == "BLOCKED"
    checks["gate_blocked"] = gate_blocked
    if not gate_blocked:
        errors.append(f"gate_state is {commands.get('gate_state')}, expected BLOCKED")

    # Check 3: public_release_allowed == False
    no_public = commands.get("public_release_allowed") is False
    checks["public_release_not_allowed"] = no_public
    if not no_public:
        errors.append("public_release_allowed must be False")

    # Check 4: hf_upload_allowed == False
    no_upload = commands.get("hf_upload_allowed") is False
    checks["hf_upload_not_allowed"] = no_upload
    if not no_upload:
        errors.append("hf_upload_allowed must be False")

    # Check 5: No HF upload commands
    all_commands = []
    for key in [
        "environment_setup",
        "dataset_build",
        "preflight",
        "training_dryrun",
        "training_real",
        "baseline_eval",
        "adapter_eval",
        "manifest",
        "summary",
        "secret_scan",
    ]:
        all_commands.extend(commands.get(key, []))
    has_hf_upload = any(
        "hf upload" in cmd or "huggingface-cli upload" in cmd or "huggingface_hub.upload" in cmd for cmd in all_commands
    )
    checks["no_hf_upload_commands"] = not has_hf_upload
    if has_hf_upload:
        errors.append("HF upload commands found in generated commands")

    # Check 6: No forbidden commit artifacts as committable outputs
    forbidden = commands.get("forbidden_actions", [])
    # This is informational - we check that forbidden_actions list mentions key items
    key_forbidden = ["GGUF", "adapter", "HF", "checkpoint"]
    forbidden_adequate = all(any(k.lower() in f.lower() for f in forbidden) for k in key_forbidden)
    checks["forbidden_actions_adequate"] = forbidden_adequate
    if not forbidden_adequate:
        warnings.append("Forbidden actions list may be missing key items (GGUF, adapter, HF, checkpoint)")

    result = {
        "valid": len(errors) == 0,
        "errors": errors,
        "warnings": warnings,
        "checks": checks,
        "unsupported_flags_found": unsupported_found,
        "gate_state": commands.get("gate_state"),
        "public_release_allowed": commands.get("public_release_allowed"),
        "hf_upload_allowed": commands.get("hf_upload_allowed"),
    }

    if args.json_output:
        print(json.dumps(result, indent=2))
    else:
        print("\n" + "=" * 60)
        print("  Private SFT Command Validation")
        print("=" * 60)
        for check_name, passed in checks.items():
            symbol = "\u2713" if passed else "\u2717"
            print(f"  {symbol} {check_name}")
        if errors:
            print("\n  ERRORS:")
            for e in errors:
                print(f"    X {e}")
        if warnings:
            print("\n  WARNINGS:")
            for w in warnings:
                print(f"    ! {w}")
        print("\n" + "=" * 60)
        if result["valid"]:
            print("  Result: PASS")
        else:
            print("  Result: FAIL")
        print("=" * 60)

    sys.exit(0 if result["valid"] else 1)


if __name__ == "__main__":
    main()
